name: Deploy SQL Scripts to PostgreSQL in GCP

on:
  push:
    branches: [main]

jobs:
  deploy-db:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Authenticate to GCP  
      uses: google-github-actions/auth@v1  
      with: 
        credentials_json: ${{ secrets.FEWS_SA_KEY }}

    - name: Install PostgreSQL client
      run: sudo apt-get install -y postgresql-client

    - name: Start Cloud SQL Proxy
      run: |
        wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
        chmod +x cloud_sql_proxy
        ./cloud_sql_proxy -dir=/cloudsql -instances=tidy-crane-440110-e1:asia-south1:fews=tcp:5432 &

    - name: Execute SQL Scripts
      env:
        PGHOST: 34.47.174.243
        PGPORT: 5432
        PGUSER: postgres
        PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        PGDATABASE: postgres
      run: |
        psql -c "DROP DATABASE IF EXISTS fews;"
        psql -c "CREATE DATABASE fews;"
        psql -d fews -f ssc_chittoor.sql
