name: Deploy SQL Scripts to PostgreSQL on GCP

on:
  push:
    branches: [main]

jobs:
  deploy-db:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up GCP Credentials
      uses: actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.FEWS_SA_KEY }}

    - name: Execute SQL Scripts
      run: |
        gcloud sql connect fews --user=postgres --password=rocky --host=34.47.174.243 --port=5432
        pg_restore --verbose --clean --single-transaction --dbname="postgres://postgres:rocky@localhost:5432/postgres" --format=plain --file="ssc_chittoor.sql"
