name: Deploy SQL Scripts to PostgreSQL

on:
  push:
    branches: [main]

jobs:
  deploy-db:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Authenticate to GCP  
      uses: google-github-actions/auth@v1  
      with: 
        credentials_json: ${{ secrets.FEWS_SA_KEY }}

    - name: Install PostgreSQL client
      run: sudo apt-get install -y postgresql-client

    - name: Execute SQL Scripts
      env:
        PGHOST: 34.47.174.243
        PGPORT: 5432
        PGUSER: postgres
        PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        PGDATABASE: postgres
      run: |
        psql -c "DROP DATABASE IF EXISTS fews;"
        psql -c "CREATE DATABASE fews;"
        psql -d fews -f ssc_chittoor.sql
